services:
  landing:
    ports:
      - "8080:80"

  website:
    build:
      args:
        NEXT_PUBLIC_SITE_URL: http://localhost:3000
    environment:
      NEXT_PUBLIC_SITE_URL: http://localhost:3000
    ports:
      - "3000:3000"
